#168781751 reset password
andela/eagle-bn-frontend pull request #16
Opened 2019-12-05 11:29 UTC by urbanishimwe

#### What does this PR do?
- As a user, I should be able to reset my password
#### Description of Task to be completed?
Given a user is registered in barefoot, the should be able to request password reset notification.
#### How should this be manually tested?
After follwoing the instructions in [README](https://github.com/andela/eagle-bn-frontend/blob/develop/README.md)
**use routes**
`request reset: /password/reset` and then check your email and click on the link provided
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[story](https://www.pivotaltracker.com/story/show/168781751)
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/33803574/70231565-3f55a500-1763-11ea-8d76-003224140ff2.png)
![image](https://user-images.githubusercontent.com/33803574/70231573-441a5900-1763-11ea-932f-bba51e37c036.png)

#### Questions:

2019-12-05 12:01 UTC, lemoissonM requested changes

2019-12-05 12:01 UTC, lemoissonM commented on src/App/Pages/request.reset.password.page.js
> +		console.log(requestResetStatus);
remove console

2019-12-05 12:01 UTC, lemoissonM commented on src/__tests__/components/request.reset.password.test.js
> +		expect(wrapper.find('div.mainContainer')).toExist();
try also to test for something else. You are testing the same thing everywhere

2019-12-05 12:01 UTC, lemoissonM commented on src/__tests__/components/reset.password.test.js
> +		expect(wrapper.find('div.mainContainer')).toExist();
the same here, try to test different things to ensure the feature is working properly

2019-12-05 12:02 UTC, lemoissonM commented
great job @urbanishimwe , However consider the above feedback

2019-12-05 12:54 UTC, swaibat requested changes

2019-12-05 12:54 UTC, swaibat commented on src/App/Pages/reset.password.page.js
> +				</div>
@urbanishimwe great job but we don't need to create new messages here since the message is specified in the backend api

2019-12-05 12:54 UTC, swaibat commented on src/App/Pages/request.reset.password.page.js
> +			return (
great job @urbanishimwe  but after success what will happen

2019-12-05 12:54 UTC, swaibat commented on src/App/Pages/reset.password.page.js
> +					your password was updated successfully
@urbanishimwe great job but we don't need to create new messages here since the message is specified in the backend api

2019-12-05 12:54 UTC, swaibat commented on src/App/Pages/reset.password.page.js
> +				<div className='alert alert-success' role='alert'>
@urbanishimwe great job but after success true to redirect a user to login

2019-12-06 05:17 UTC, lemoissonM approved these changes

2019-12-06 06:58 UTC, swaibat approved these changes

2019-12-06 07:18 UTC, merged