#168781755 view requests
andela/eagle-bn-frontend pull request #20
Opened 2019-12-11 13:16 UTC by lemoissonM

#### What does this PR do?
User should be able to view a list of requests he has made
#### Description of Task to be completed?
- Create request views
- Create a list of request
- Write tests for requests

#### How should this be manually tested?
- clone the repository
- run npm i
- run `npm run test`
- run `npm run dev:open`
- access the route ` /requests` with ` GET` method
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/168781755

#### Screenshots (if appropriate)
<img width="1148" alt="Screen Shot 2019-12-11 at 15 15 59" src="https://user-images.githubusercontent.com/49560334/70624552-2f3d3a00-1c29-11ea-9315-27ee4c3baf54.png">

2019-12-11 13:37 UTC, urbanishimwe approved these changes

2019-12-11 14:10 UTC, Crispy-rw approved these changes

2019-12-12 10:24 UTC, swaibat requested changes
@lemoissonM  great job but try to work on those feedbacks otherwise great job your rocking

2019-12-12 10:24 UTC, swaibat commented on src/App/Components/Header.js
>  				<html lang='en' />
@lemoissonM  great job but remove this because it is in the `Public HTML file` and of cause <>

2019-12-12 10:24 UTC, swaibat commented on src/__tests__/components/request.list.test.js
> +		console.log(wrapper.html());
and this

2019-12-12 10:24 UTC, swaibat commented on src/App/Components/SideNav.js
> +	console.log(active);
also this

2019-12-12 14:37 UTC, swaibat approved these changes

2019-12-12 14:40 UTC, merged