#17012404: single accommodations
andela/eagle-bn-frontend pull request #26
Opened 2019-12-17 09:35 UTC by Crispy-lang

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2019-12-17 17:59 UTC, swaibat requested changes

2019-12-17 17:59 UTC, swaibat commented on src/Api/index.js
> +		return await axios.get(`${BASE_URL}accommodations/${id}`);
great job @crispy but your using wastelessly await and return statement its better you remove async function and leave it as a row function

2019-12-17 17:59 UTC, swaibat commented on src/Api/index.js
> +		return await axios.get(`${BASE_URL}accommodations/${id}`);
you can idealy see as in examples above

2019-12-18 09:07 UTC, urbanishimwe approved these changes

2019-12-18 11:11 UTC, swaibat approved these changes

2019-12-18 11:13 UTC, lemoissonM approved these changes

2019-12-18 11:35 UTC, merged