#168781749 setup story book
andela/eagle-bn-frontend pull request #5
Opened 2019-11-27 04:19 UTC by lemoissonM

#### What does this PR do?
- setup storybook
#### Description of Task to be completed?
- install storybook
#### How should this be manually tested?
- run npm install
- run npm run storybook
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/168781749
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2019-11-27 10:14 UTC, swaibat requested changes

2019-11-27 10:14 UTC, swaibat commented on .storybook/webpack.config.js
> +    test: /.(jpg|jpeg|png|gif|svg)$/,
great job @lemoissonM  among these extensions I highly recommend you to add `.webp` since we are going to use it largely in our frontend app

2019-11-27 10:28 UTC, swaibat approved these changes

2019-11-28 10:01 UTC, urbanishimwe approved these changes

2019-12-03 14:08 UTC, merged